version: '3'
services:
  app:
    build: ./app/
    ports:
      - "5001:5000"
    volumes:
      - ./app:/code
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./redis/volumes:/data
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/volumes:/data/db
